import { minify } from "html-minifier";
import Processor from "./Processor.js";

export class HtmlMinifier extends Processor {
  constructor(options) {
    super(options, {
      test: (direntData) => direntData.ext === ".html",
      minifierOptions: {
        includeAutoGeneratedTags: true,
        removeAttributeQuotes: true,
        removeComments: true,
        removeRedundantAttributes: true,
        removeScriptTypeAttributes: true,
        removeStyleLinkTypeAttributes: true,
        sortClassName: true,
        useShortDoctype: true,
        collapseWhitespace: true,
      },
    });
  }

  async process(dist) {
    dist.content = minify(dist.content, this.options.minifierOptions);
    return dist;
  }
}

export default HtmlMinifier;
