export const config = {
  force: false,
  verbosity: 3,
  logFile: "",
  reportFile: "",

  src: "",
  dist: "",

  processors: [
    new TemplatesProcessor(),
    new HtmlPartialInjector(),
    new CssPartialInjector(),
    new JsonPartialInjector({
      extensions: ["json", "webmanifest"],
    }),
    new HtmlMinifier({
      options: {
        includeAutoGeneratedTags: true,
        removeAttributeQuotes: true,
        removeComments: true,
        removeRedundantAttributes: true,
        removeScriptTypeAttributes: true,
        removeStyleLinkTypeAttributes: true,
        sortClassName: true,
        useShortDoctype: true,
        collapseWhitespace: true,
      },
    }),
    new CssMinifier({
      options: {},
    }),
    new JsMinifier({
      options: {},
    }),
    new JsonMinifier({
      extensions: ["json", "webmanifest"],
    }),
    new ImgProcessor({
      extensions: [],
      resize: true,
      resizeWidth: [320, 640, 1280, 1920, 2560],
      convert: true,
      convertTypes: ["avif", "webp", "jpg"],
      keepOriginal: true,
    }),
  ],

  data: {},
};

export default config;
