import path from "path";

export const config = {
  force: false,
  verbosity: 3,
  logFile: "",
  reportFile: "",

  src: "",
  dist: "",

  processors: [
    new TemplatesProcessor({
      force: false,
      src: "",
      dist: "",
    }),
    new PartialsProcessor({
      force: false,
      src: "",
      dist: "",
      htmlPartialAttribute: "data-swappski-partial",
      cssPartialDeclaration: "-swappski-partial",
      jsonPartialField: "_swappski_partial",
    }),
    new HtmlProcessor({
      force: false,
      minify: true,
      minifyOptions: {
        includeAutoGeneratedTags: true,
        removeAttributeQuotes: true,
        removeComments: true,
        removeRedundantAttributes: true,
        removeScriptTypeAttributes: true,
        removeStyleLinkTypeAttributes: true,
        sortClassName: true,
        useShortDoctype: true,
        collapseWhitespace: true,
      },
    }),
    new CssProcessor({
      force: false,
      minify: true,
      minifyOptions: {},
      transformImagesToBase64: true,
      transformImagesToBase64Options: {},
    }),
    new JsProcessor({
      force: false,
      minify: true,
      minifyoptions: {},
    }),
    new JsonProcessor({
      force: false,
      minify: true,
      extensions: ["json", "webmanifest"],
    }),
    new ImgProcessor({
      force: false,
      extensions: [],
      resize: true,
      resizeWidth: [320, 640, 1280, 1920, 2560],
      convert: true,
      convertTypes: ["avif", "webp", "jgp"],
      keepOriginal: true,
    }),
  ],

  data: {},
};

export default config;
